spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      auto-commit: false
  output:
    ansi:
      enabled: always
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  jackson:
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true
  batch:
    job:
      name: simpleJob

