spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      auto-commit: false
    ansi:
      enabled: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
  sql:
    init:
      mode: always
